modLoader="javafml"
loaderVersion="[26,)"
license="MIT"

[[mods]]
modId="trabenium"
version="1.0.0"
displayName="Trabenium"
authors="Revery"
description="Compatibility bridge between Entity Model Features (EMF), Entity Texture Features (ETF), Entity Sound Features (ESF), and Sodium."

[[dependencies.trabenium]]
modId="neoforge"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.trabenium]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="BOTH"

[[dependencies.trabenium]]
modId="entity_texture_features"
type="required"
versionRange="[6.1,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.trabenium]]
modId="entity_model_features"
type="required"
versionRange="[2.2,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.trabenium]]
modId="entity_sound_features"
type="required"
versionRange="[1.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.trabenium]]
modId="sodium"
type="required"
versionRange="[0.6,)"
ordering="AFTER"
side="CLIENT"
